# Generated by Django 4.0.2 on 2022-03-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_interesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registreduser',
            name='words',
            field=models.ManyToManyField(to='how_interesting.Word'),
        ),
    ]
