# Generated by Django 4.0.2 on 2022-03-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_interesting', '0002_registreduser_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='count',
        ),
    ]
